version: "3"

services:
  backend:
    build:
      context: ./Backend
    command: gunicorn ZZAZO.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./Frontend
    volumes:
      - react_build:/Frontend/build

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/frontend
      - ./nginx/nginx-setup.conf:/etc/nginx/sites-available/j7b307.p.ssafy.io:ro
      # - ../certbot/conf:/etc/letsencrypt # 추가
      # - ../certbot/www:/var/www/certbot # 추가
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  # mongodb:
  #   image: mongo
  #   container_name: mongodb
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./mongodb:/data/db
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=1234
  #     - MONGO_INITDB_DATABASE=mydb

  # mysql:
  #   image: mysql:5.7
  #   volumes:
  #     - todo-mysql-data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: <your-password>
  #     MYSQL_DATABASE: todos

volumes:
  react_build:
